### ISSUE TITLE
Maven packaging a generated file

### ISSUE THREAD

**Issue by jpalmerpivotal** [imsweb/validation-translation#10]
I am pretty inexperienced in Java, and I am having difficulty getting the output to package as I expect. Part of my problem is that I am not sure how to work with groovy.

I was wondering if you either have some scripts/settings/advice you could share for packaging the output directory as you did for `validation-edits-naaccr-translated` and SEER?

**Comment by depryf** [comment]
Using pre-compiled edits is not a requirement; you should be able to run your validation by just loading the XML file. I would recommend you look into the pre-compiled stuff only when your entire process works well and you want to optimize it.

I setup the other translated edits as their own Gradle project, but those projects are internal and not available on GitHub. Their setup is very similar to this validation-translation project, except that the source code is Groovy and not Java (and so they use src/main/groovy instead of src/main/java).  The source files created by the translation are meant to be plugged directly into a Gradle project (they follow the Gradle project structure for source files).

And so I don't really have any scripts for that part; when I want to translate a new metafile, I run the translation, it updates my source files directly in the project that contain those translated edits, and then I use a Gradle task to package my (groovy) source code into a JAR and to release them in Maven Central. That's all standard Gradle stuff.

**Comment by jpalmerpivotal** [comment]
Hi again, the validation code is working very nicely for us. I have been bothered by the slow startup time when debugging, so I tried to look into into the compilation with groovy. I have run into a variety of issues. I am not a native Java coder so this is all quite foreign to me even before incorporating groovy.
Could you share the gradle configuration you use for making that package? I have been messing around with groovyc, gradle and maven to little avail all of today.

**Comment by depryf** [comment]
So the translation process has an option to create the Groovy source code (in addition to the edits XML file). That source code needs to be generated into another Gradle project. Once that's done, there is nothing special about that other project, other than the fact it's a groovy project. You just need to apply the "groovy" plugin in Gradle (for good measure, I also apply the "java-library" plugin, but I am not sure that's necessary).  And then you can run the build by typing "gradlew assemble" and that should compile your Groovy source code and create a JAR file. After that, you still have to figure out how to include that JAR file into your other projects (we release ours on Maven Central, but I don't know if that's an option for you); that release step is outside the scope of translating edits though.

Here is how the translation configuration looks like for NAACCR edits:

```java
TranslationConfiguration conf = new TranslationConfiguration();
conf.setWorkingDirectoryPath(<folder containing the metafile>);
conf.setPreviousWorkingDirectoryPath(<folder containing the previously translated metafile>); // optional
conf.setMetafileName(<metafile filename to translate>);
conf.setTranslationPrefix("naaccr");
conf.setNaaccrVersion("210");
conf.setMinValidationEnginVersion("6.6");
conf.setIdGeneration(IdGeneration.INCREMENTAL);
conf.setNumCompilationThreads(4);
conf.setGenerateGroovySourceCode(true);
conf.setGroovySourceCodeDirectoryPath(new File(System.getProperty("user.dir"), "validation-edits-naaccr-translated").getPath());
conf.setGroovySourceCodePackage("com.imsweb.validation.edits.translated.naaccr");
conf.setXmlFileSourcePath("edits/translated/naaccr");
conf.setGroovySourceCodeNumFiles(10); // only needed because NAACCR metafile is really big
```

And here is how a simplified build file would look like (I removed all the logic related to the release process and the testing dependencies):
``` groovy
plugins {
    id 'java-library'
    id 'groovy'
}

group = 'com.imsweb'
version = file('VERSION').text.trim()

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

tasks.withType(JavaCompile) {
    options.compilerArgs << "-Xlint:all"
}

groovydoc.enabled = false

// generate javadoc and sources (required by Nexus)
java {
    withJavadocJar()
    withSourcesJar()
}

// where to find the project dependencies
repositories {
    mavenCentral()
}

// project dependencies
dependencies {
    implementation 'com.imsweb:validation:2.25'
}
```

The one thing that the translation doesn't do is update the VERSION file with the new version of the translated edit. That's why the build file uses a VERSION file instead of hard-coding the version (it's easier to update the version in a TEXT file that only contains that version than to update a full build file. That's a detail and you can even update it by hand each time you do a new translation. But that VERSION is going to be very important if you release your JAR file in some repository.

Take a look at this and let me know if that helps or not.

**Comment by jpalmerpivotal** [comment]
Thank you so much for this! It was very helpful and I was able to put together a bunch of pieces I couldn't quite understand with the help you gave. My test setup time is down from 30 seconds to 5 seconds which feels a lot better when trying to debug edits issues.

While I was doing this process I ran into a small issue with New York's edit `NY058` where they passed a char[] to GEN_DAYDIFF_IOP instead of a String causing compilation to fail. I just converted it to a String manually for now. I thought I would bring it to your attention, though this feels more like they did something non-standard/possibly wrong with their edit rather than something that was missed.
I suspect this is a no-op on your end, but if I run into the issue again as we add more states/metafiles update I might bring it back up. 

Again huge thanks, and very appreciative of your timely and thorough responses!

**Comment by depryf** [comment]
You are welcome!

I am glad to hear you made it work. The pre-compilation is a bit of a pain to set up but it's a pretty amazing optimization!

If at some point you want me to look into that translation issue, please provide the edit's code (or at least the snippet where you think the problem is).
