### ISSUE TITLE
Unable to parse: IfThenElseStatement

### ISSUE THREAD

**Issue by jpalmerpivotal** [imsweb/validation-translation#8]
I have pared down the failed edits to only those that are in sets that are run. 

Effected edits for this issue: 

- `N5020` :  `Autopsy Only, RX, Schema ID, Primary Site, 2018 (NPCR)`
- `PA2607`: `Z_Vendor Name`
- `PA2542`: `Z_Date of 1st Contact`
- `PA2553`: `Z_Date of Last Contact`
[PA metafile download link](https://www.naaccr.org/wp-content/uploads/2021/10/NAACCR_v22A_PA.zip)

Example error:
`> !!! Unable to parse 'Autopsy Only, RX, Schema ID, Primary Site, 2018 (NPCR)': class com.imsweb.validation.translation.language.entity.IfThenElseStatement cannot be cast to class com.imsweb.validation.translation.language.entity.ParsedTree (com.imsweb.validation.translation.language.entity.IfThenElseStatement and com.imsweb.validation.translation.language.entity.ParsedTree are in unnamed module of loader 'app')`

**Comment by jpalmerpivotal** [comment]
These were the only issues I found in edits that were included in edit sets. I will assume the others that broke were just faulty metafile setup (missing messages and such). So overall a pretty good hit rate.

**Comment by depryf** [comment]
Many metafiles are based on the NAACCR one, meaning the registry/organization takes the NAACCR one and tweak a few edits or add a few. It looks this is the case for this PA metafile.

And so it has the same syntax error as the official NAACCR one (and assuming NAACCR will fix that syntax error in their next version, I assume PA will follow that as well).

If you open that specific edit, you will see that the if statement that goes from line 40 to 53 is structured as a "if ... else ... else". 

That's not valid and cannot be translated.

I think you have two options:

1. If you know what the correct syntax is supposed to be, you can use a customized LogicResolver in the configuration that tweaks the logic of that edit before it's being translated. I *think* the second else is supposed to go with the inner-if in the first else, but that's not really obvious to me.

2. You can do nothing, take this as a well known issue that will resolve itself in the next version of the metafile. In the meantime this edit won't fail.

**Comment by depryf** [comment]
I looked at Z_Vendor Name and the syntax doesn't look correct to me either. 

It's structured this way (minus the braces, but I put them to illustrate my point):

```java
if (...) {
    return PASS;
    // some other statement
}
else
    return PASS;
}
```

There can't be statements in a given block after a return, that doesn't make sense.   

If you read the description of that edit, that first "if" is supposed to be a pre-condition (early return) in the logic, and so I think that last "else" was added by mistake.

I took a quick look at the Z_Date of 1st Contact and I think this is something similar.

At the end, I think all those errors are similar and  are related to a badly structured if statement that Genedits doesn't properly validate. 

Sometimes those errors don't create any real issue in the Genedits framework; in that case it's really difficult to get people to fix them. Other time, I can come up with a set of inputs that should return something according to the description but returns something else. In that case people are more willing to fix the bad syntax since it affects how the edit run. 

Unfortunately, the Z_Vendor Name falls in the first category. Because the extra "else" appears at the end, it will never be hit by the Genedits engine (the logic will always return before hitting that point of the edit). And so it will be difficult to explain that the syntax is "wrong" since it doesn't generate any wrong failures.

At the end, I think you can either

1. Contact the people who maintain the metafile, explain the syntax issues to them and ask them to fix that syntax.
2. Use the LogicResolver and tweak the logic yourself before it's translated.
3. Leave those edits as-is; they will never fail since they couldn't be translated.

If #1 is not an option for you, I think you should do #2. It's very simple for the Z_Vendor Name; you just have to remove the two last lines of the translated edit. I am not sure about the two other edits.  I would have to take a closer look and see if a logical tweak can easily be applied (knowing the intend of the edit).

**Comment by jpalmerpivotal** [comment]
This is why I am a firm believer that curly braces should be mandatory with all if statements...
I think my preferred solution is to contact the maintainers, so I will work on that.
I might also try to validate how the edits work in the metafiles to see whether they are actually broken as we do not want our users falsely believe they are passing a state edit that actually runs that we can't.

Big thanks for all the help!

**Comment by depryf** [comment]
There has not been any activity on this thread for a while. I am going to close it.
